/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Spell } from './types';

export const SPELLS_DATABASE: Spell[] = [
  // --- Elemental Primitives ---
  {
    id: 'light',
    name: 'Light Glyph',
    type: 'primitive',
    primaryElement: 'light',
    description: 'Generates a floating sphere of off-white or golden light. Acts as an ambient beacon, flare, or flashbang based on drawing scale.',
    lore: 'The fundamental primitive governing illumination and positive atmospheric charges. It was the first glyph discovered by the human apprentice Luz Noceda by observing the twinkling of constellations in the Boiling Isles sky.',
    discovery: 'Observed in the stars during a clear night on the knee of the Titan, mapping directly to cosmic light emissions.',
    difficulty: 'Novice',
    visualDescription: 'Creates gorgeous golden orbit spheres that float gracefully in the air, reacting to cursor movement and emitting sparkling solar dust.',
    color: '#FFEAA7',
    shadowColor: 'rgba(254, 211, 48, 0.6)',
  },
  {
    id: 'ice',
    name: 'Ice Glyph',
    type: 'primitive',
    primaryElement: 'ice',
    description: 'Generates expanding frost layers, columns, or jagged spikes. Ideal for building protective barriers, platforms, or catapulting mass.',
    lore: 'Governs local thermodynamic reduction, compression, and crystallization. Its discovery proved that glyphs are hidden in microscopic structures throughout the Isles, not just in the sky.',
    discovery: 'Discovered under magnification within the fractal geometry of a perfect snowflake landing on a sleeve.',
    difficulty: 'Novice',
    visualDescription: 'Sprouts towering, gleaming ice pillars from the canvas grid that can be shattered into interactive, bouncing icy crystal debris.',
    color: '#74B9FF',
    shadowColor: 'rgba(9, 132, 227, 0.6)',
  },
  {
    id: 'plant',
    name: 'Plant Glyph',
    type: 'primitive',
    primaryElement: 'plant',
    description: 'Causes rapid germination and organic growth, sprouting sturdy vines, blossoming flowers, and mighty root systems.',
    lore: 'Governs organic cellular expansion and botanical transmutation. It shares striking geometric parallels with historical terrestrial alchemical symbols for the Earth and Sun.',
    discovery: 'Observed under magnification on the veins of a living wild flora leaf, revealing hidden circular glyph codes.',
    difficulty: 'Novice',
    visualDescription: 'Grows procedural, winding botanical vines and climbing leafy creepers directly across the canvas, complete with blossoming wildflowers.',
    color: '#55EFC4',
    shadowColor: 'rgba(0, 184, 148, 0.6)',
  },
  {
    id: 'fire',
    name: 'Fire Glyph',
    type: 'primitive',
    primaryElement: 'fire',
    description: 'Triggers local thermal combustion, venting high-energy fire spheres, localized flame pillars, or intense heatwaves.',
    lore: 'Governs rapid kinetic release and atomic excitation. Highly volatile and prone to sudden explosive release if drawn with structural defects.',
    discovery: 'Recovered from residue soot and glowing smoldering ash inside a sports pitch after a high-voltage Grudgby match.',
    difficulty: 'Novice',
    visualDescription: 'Combusts drawn strokes with fiery explosions. Launches blazing fireballs that explode into sparks and swirling soot particles on collision.',
    color: '#FF7675',
    shadowColor: 'rgba(214, 48, 49, 0.6)',
  },

  // --- Combinatory Spells ---
  {
    id: 'sleep_mist',
    name: 'Sleep Mist Spell',
    type: 'combinatory',
    primaryElement: 'ice',
    description: 'Creates a heavy, swirling indigo-purple vapor that gently slows down and induces a deeply tranquil soporific state on environmental objects.',
    lore: 'By blending the rapid thermal crystallization of the Ice glyph with the active kinetic heat of the Fire glyph, a highly distinct, dense mist is generated. Inscaping a small vacant node at the base mimics passing environmental flowers (like sleeping nettles) into the spell parameters.',
    discovery: 'Devised by blending Fire and Ice to establish a rapid thermal differential, producing steam that suspends sleep-inducing mineral dust.',
    difficulty: 'Apprentice',
    recipe: {
      elements: ['ice', 'fire'],
      layout: 'Ice glyph on the right hemisphere, Fire glyph on the left, bound in a single ring.',
    },
    visualDescription: 'Fills the screen with beautiful, lavender-indigo gaseous cloud particles. Active gravity decreases and all physics elements slow down as if in a peaceful dream state.',
    color: '#A29BFE',
    shadowColor: 'rgba(108, 92, 231, 0.6)',
  },
  {
    id: 'wind_vortex',
    name: 'Tornado / Wind Vortex',
    type: 'combinatory',
    primaryElement: 'light',
    description: 'Assembles secondary elemental loops to generate severe, localized barometric pressure gradients, yielding a continuous, rotating cyclonic vortex.',
    lore: 'An advanced array organizing a Light glyph in the peripheral circuit, an Ice glyph anchoring the core, and three Fire glyphs arranged radially. The sudden thermal chaos spirals air currents into a self-feeding meteorological vortex.',
    discovery: 'Observed during severe storms at sea, where atmospheric light flashes collided with thermal boundaries of volcanos.',
    difficulty: 'Adept',
    recipe: {
      elements: ['light', 'ice', 'fire'],
      layout: 'Ice anchor in the center, 3 Fire glyphs on radial nodes, 1 Light glyph on the outer boundary.',
    },
    visualDescription: 'Spawns a powerful, interactive swirling cyclone. Any lighter debris, spheres, or embers on the canvas are sucked into its vortex and spiraled upward with high speed.',
    color: '#81ECEC',
    shadowColor: 'rgba(0, 206, 201, 0.6)',
  },
  {
    id: 'invisibility',
    name: 'Invisibility Shroud',
    type: 'combinatory',
    primaryElement: 'light',
    description: 'Bends local photon pathways seamlessly around the user, rendering them completely unseen. The duration is strictly bound to the ability to hold one\'s breath.',
    lore: 'A masterwork optical circle featuring a Light glyph anchor, modified by an offset secondary Light glyph and balanced by Ice glyphs in the lower segments. This triggers a total refraction prism, canceling incoming shadows and projections.',
    discovery: 'Synthesized by covert intelligence operatives wishing to pass through hostile boundaries undetected.',
    difficulty: 'Adept',
    recipe: {
      elements: ['light', 'ice'],
      layout: 'Light glyph anchor, offset secondary Light glyph at top-left, dual Ice glyphs at bottom-left and bottom-right nodes.',
    },
    visualDescription: 'Fades the interface, mouse cursors, and custom strokes into transparent refractive overlays. Initiates a rhythmic "Lungs/Breath Gauge"; exhalations or clicking breaks the light bending.',
    color: '#DFE6E9',
    shadowColor: 'rgba(178, 190, 195, 0.5)',
  },
  {
    id: 'safety_hover',
    name: 'Safety Hover Array',
    type: 'combinatory',
    primaryElement: 'light',
    description: 'Establishes a localized anti-gravity zone, dramatically decelerating and suspending falling masses before ground-surface impact.',
    lore: 'A defensive array engineered to decelerate falls. By pacing Light at the absolute core with balanced Ice (top-right) and Fire (bottom-left) modify nodes, the gravity vector is temporarily canceled.',
    discovery: 'Devised by emergency cartographers to survive sudden drops while scaling the vertical cliffs of the Titan\'s ribcage.',
    difficulty: 'Apprentice',
    recipe: {
      elements: ['light', 'ice', 'fire'],
      layout: 'Central Light anchor, modified by Ice (top-right) and Fire (bottom-left) to lock vertical momentum.',
    },
    visualDescription: 'Generates pulsing, soft-blue gravity fields. Any falling objects entering the safety bubble are gently slowed to a crawl and carry a protective cyan glow.',
    color: '#00CEC9',
    shadowColor: 'rgba(0, 184, 148, 0.6)',
  },
  {
    id: 'petrification',
    name: 'Petrification Curse',
    type: 'combinatory',
    primaryElement: 'ice',
    description: 'A dark, devastating transmutation spell. Violently reorganizes organic tissue, turning active matter into brittle, crumbly stone.',
    lore: 'An extremely dangerous and forbidden spell that forces material structures into stagnant cellular decay. Demands three Ice nodes to completely freeze thermal vibration, coupled with two Plant elements that crystallize cellular fiber into stone mineral deposits.',
    discovery: 'Drawn from ancient inscriptions on Emperor Belos\'s inner castle walls. Historically used for public petrification ceremonies.',
    difficulty: 'Master',
    recipe: {
      elements: ['ice', 'plant'],
      layout: '3 Ice glyphs and 2 Plant glyphs connected by linear channels in a dual nested frame.',
    },
    visualDescription: 'Slowly petrifies the active vines, fireballs, and light spheres into grey, heavy stony blocks that tumble to the bottom and crack apart upon clicking.',
    color: '#636E72',
    shadowColor: 'rgba(45, 52, 54, 0.8)',
  },
  {
    id: 'monster_arm',
    name: 'Abomination Mutation',
    type: 'combinatory',
    primaryElement: 'plant',
    description: 'Inscribes on clothing to sprout a powerful, physical, self-animating and highly aggressive biomechanical limb made of thick organic vines.',
    lore: 'Utilizes a duo of Plant glyphs (rapid cellular multiplication) and Fire glyphs (kinetic animation energy). This bypasses traditional abomination slime, building a violent muscular plant limb directly connected to the user\'s somatic control.',
    discovery: 'Adapted from wild, forbidden plant-human bio-fusions discovered in old Boiling Isles ruins.',
    difficulty: 'Master',
    recipe: {
      elements: ['plant', 'fire'],
      layout: 'Two Plant glyphs for material mass, and two Fire glyphs for somatic kinetic movement.',
    },
    visualDescription: 'Sprouts a massive multi-jointed wooden arm from the point of drawing that stretches, swings, and claws dynamically toward the user\'s mouse mouse, grabbing debris!',
    color: '#E17055',
    shadowColor: 'rgba(225, 112, 85, 0.6)',
  },
  {
    id: 'teleportation',
    name: 'Titan Spatial Teleportation',
    type: 'combinatory',
    primaryElement: 'fire',
    description: 'Triggers absolute spatial displacement. Spawns two interlocking portal rings to translate matter instantly between two locations.',
    lore: 'The apex of glyph engineering. A tetrameric design featuring 1 Fire anchor, surrounded by 5 Ice, 8 Plant, and 8 Fire peripheral modifier glyphs mapped on strict diagonal celestial axes. Connects two folding points of the Boiling Isles\' ambient magic grid.',
    discovery: 'A lost ritual recorded on the stone chambers of the Titan\'s skull, historically used to navigate instantly across different regions.',
    difficulty: 'Titan-Level',
    recipe: {
      elements: ['fire', 'ice', 'plant'],
      layout: 'Large parent-child matrix featuring 1 Fire core, interlocking satellite rings storing 5 Ice, 8 Plant, and 8 Fire nodes.',
    },
    visualDescription: 'Deploys two spatial portal circles on the canvas (Orange Portal A, Blue Portal B). Bouncing objects, particles, and spheres that drop into Portal A are fired out of Portal B instantly, complete with cosmic ripples!',
    color: '#FD79A8',
    shadowColor: 'rgba(253, 121, 168, 0.7)',
  },
];
